add_newline = false

[directory]
prefix = "in "
truncate_to_repo = true
disabled = false

[character]
symbol = "âœ"

[package]
disabled = true

[kubernetes]
disabled = false

[time]
disabled = false
format = "ğŸ•™ [ %T ]"
